name = "jucodex-worker"
main = "src/index.js"
compatibility_date = "2025-02-01"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "jucodex"

[vars]
STATIC_ORIGIN = "https://static.jucodex.com"
BACKEND_HOST = "alb.jucodex.com"
BACKEND_PROTO = "https"
BACKEND_PORT = ""
